
logging:
  file: F:\java\springboot\sell.log
  pattern:
    console: "%d - %msg%n"
# 数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.102:3306/sell?characterEncoding=utf-8&useSSL=false
# 打印sql
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null # 空字段不返回
# 项目路径
server:
  context-path: /sell
# WeChat配置
wechat:
  AppId: wx5c03e8698267f02e
  Secret: 74f0139cd49d10017c8be89f79277802
  MchId:
  MchKey:
  NotifyUrl: https://pay.weixin.qq.com/pay/notify

